-- MySQL Script generated by MySQL Workbench
-- lun 10 avr 2017 12:02:23 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database` DEFAULT CHARACTER SET utf8 ;
USE `database` ;

-- -----------------------------------------------------
-- Table `database`.`Personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Personne` (
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Genre` VARCHAR(45) NULL,
  PRIMARY KEY (`Nom`, `Numero`, `Prenom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Auteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Auteur` (
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Genre` VARCHAR(45) NULL,
  PRIMARY KEY (`Nom`, `Prenom`, `Numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Directeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Directeur` (
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Genre` VARCHAR(45) NULL,
  PRIMARY KEY (`Nom`, `Prenom`, `Numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Producteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Producteur` (
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Genre` VARCHAR(45) NULL,
  PRIMARY KEY (`Nom`, `Prenom`, `Numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Acteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Acteur` (
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `Genre` VARCHAR(45) NULL,
  PRIMARY KEY (`Nom`, `Prenom`, `Numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Oeuvre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Oeuvre` (
  `Reference` INT NOT NULL,
  `Titre` VARCHAR(45) NULL,
  `AnneeSortie` INT NULL,
  `Note` INT NULL,
  PRIMARY KEY (`Reference`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Film` (
  `Reference` INT NOT NULL,
  `Titre` VARCHAR(45) NULL,
  `AnneeSortie` INT NULL,
  `Note` INT NULL,
  PRIMARY KEY (`Reference`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Serie` (
  `Reference` INT NOT NULL,
  `Titre` VARCHAR(45) NULL,
  `AnneeSortie` INT NULL,
  `Note` INT NULL,
  `AnneeFin` INT NULL,
  PRIMARY KEY (`Reference`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Episode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Episode` (
  `Reference` INT NOT NULL,
  `Titre` VARCHAR(45) NULL,
  `AnneeSortie` INT NULL,
  `Note` INT NULL,
  `TitreE` VARCHAR(45) NULL,
  `NumeroE` INT NULL,
  `DateSortie` DATE NULL,
  PRIMARY KEY (`Reference`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Saison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Saison` (
  `NumeroS` INT NOT NULL,
  `NombreEpisodes` VARCHAR(45) NULL,
  `SReference` INT NULL,
  PRIMARY KEY (`NumeroS`),
  INDEX `Reference_idx` (`SReference` ASC),
  CONSTRAINT `Reference`
    FOREIGN KEY (`SReference`)
    REFERENCES `database`.`Serie` (`Reference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Pays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Pays` (
  `Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Genre` (
  `Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Langue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Langue` (
  `Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Administrateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Administrateur` (
  `AdresseMail` VARCHAR(45) NOT NULL,
  `motDePasse` VARCHAR(45) NULL,
  PRIMARY KEY (`AdresseMail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Role` (
  `Role` VARCHAR(45) NOT NULL,
  `PNom` VARCHAR(45) NULL,
  `PPrenom` VARCHAR(45) NULL,
  `PNumero` INT NULL,
  `OReference` INT NULL,
  PRIMARY KEY (`Role`),
  INDEX `Reference_idx` (`OReference` ASC),
  INDEX `Nom_idx` (`PNom` ASC),
  INDEX `Prenom_idx` (`PPrenom` ASC),
  INDEX `Numero_idx` (`PNumero` ASC),
  CONSTRAINT `Nom`
    FOREIGN KEY (`PNom`)
    REFERENCES `database`.`Acteur` (`Nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Prenom`
    FOREIGN KEY (`PPrenom`)
    REFERENCES `database`.`Acteur` (`Nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Numero`
    FOREIGN KEY (`PNumero`)
    REFERENCES `database`.`Acteur` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Reference`
    FOREIGN KEY (`OReference`)
    REFERENCES `database`.`Oeuvre` (`Reference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Ecrit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Ecrit` (
  `ANom` VARCHAR(45) NOT NULL,
  `APrenom` VARCHAR(45) NOT NULL,
  `ANumero` VARCHAR(45) NOT NULL,
  `OReference` INT NOT NULL,
  PRIMARY KEY (`ANom`, `APrenom`, `ANumero`, `OReference`),
  INDEX `Reference_idx` (`OReference` ASC),
  INDEX `Numero_idx` (`ANumero` ASC),
  INDEX `Prenom_idx` (`APrenom` ASC),
  CONSTRAINT `Nom`
    FOREIGN KEY (`ANom`)
    REFERENCES `database`.`Auteur` (`Nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Prenom`
    FOREIGN KEY (`APrenom`)
    REFERENCES `database`.`Auteur` (`Nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Numero`
    FOREIGN KEY (`ANumero`)
    REFERENCES `database`.`Auteur` (`Nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Reference`
    FOREIGN KEY (`OReference`)
    REFERENCES `database`.`Oeuvre` (`Reference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Produit` (
  `PNom` VARCHAR(45) NOT NULL,
  `PPrenom` VARCHAR(45) NOT NULL,
  `PNumero` VARCHAR(45) NOT NULL,
  `OReference` INT NOT NULL,
  PRIMARY KEY (`PNom`, `PPrenom`, `PNumero`, `OReference`),
  INDEX `Prenom_idx` (`PPrenom` ASC),
  INDEX `Numero_idx` (`PNumero` ASC),
  INDEX `Reference_idx` (`OReference` ASC),
  CONSTRAINT `Nom`
    FOREIGN KEY (`PNom`)
    REFERENCES `database`.`Producteur` (`Nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Prenom`
    FOREIGN KEY (`PPrenom`)
    REFERENCES `database`.`Producteur` (`Nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Numero`
    FOREIGN KEY (`PNumero`)
    REFERENCES `database`.`Producteur` (`Nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Reference`
    FOREIGN KEY (`OReference`)
    REFERENCES `database`.`Oeuvre` (`Reference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Dirige`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Dirige` (
  `DNom` VARCHAR(45) NOT NULL,
  `DPrenom` VARCHAR(45) NOT NULL,
  `DNumero` VARCHAR(45) NOT NULL,
  `OReference` INT NOT NULL,
  PRIMARY KEY (`DNom`, `DPrenom`, `DNumero`, `OReference`),
  INDEX `Reference_idx` (`OReference` ASC),
  INDEX `Numero_idx` (`DNumero` ASC),
  INDEX `Prenom_idx` (`DPrenom` ASC),
  CONSTRAINT `Nom`
    FOREIGN KEY (`DNom`)
    REFERENCES `database`.`Directeur` (`Nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Prenom`
    FOREIGN KEY (`DPrenom`)
    REFERENCES `database`.`Directeur` (`Nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Numero`
    FOREIGN KEY (`DNumero`)
    REFERENCES `database`.`Directeur` (`Nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Reference`
    FOREIGN KEY (`OReference`)
    REFERENCES `database`.`Oeuvre` (`Reference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`EstTournee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`EstTournee` (
  `PNom` VARCHAR(45) NOT NULL,
  `OReference` INT NOT NULL,
  PRIMARY KEY (`PNom`, `OReference`),
  INDEX `Reference_idx` (`OReference` ASC),
  CONSTRAINT `Nom`
    FOREIGN KEY (`PNom`)
    REFERENCES `database`.`Pays` (`Nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Reference`
    FOREIGN KEY (`OReference`)
    REFERENCES `database`.`Oeuvre` (`Reference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`EstJouee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`EstJouee` (
  `LNom` VARCHAR(45) NOT NULL,
  `OReference` INT NOT NULL,
  PRIMARY KEY (`LNom`, `OReference`),
  INDEX `Reference_idx` (`OReference` ASC),
  CONSTRAINT `Nom`
    FOREIGN KEY (`LNom`)
    REFERENCES `database`.`Langue` (`Nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Reference`
    FOREIGN KEY (`OReference`)
    REFERENCES `database`.`Oeuvre` (`Reference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`GenreOeuvre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`GenreOeuvre` (
  `GNom` VARCHAR(45) NOT NULL,
  `OReference` INT NOT NULL,
  PRIMARY KEY (`GNom`, `OReference`),
  CONSTRAINT `Nom`
    FOREIGN KEY ()
    REFERENCES `database`.`Genre` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Reference`
    FOREIGN KEY ()
    REFERENCES `database`.`Oeuvre` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
