
LOAD DATA LOCAL INFILE '/tmp/import.txt' INTO TABLE Personne FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE '/tmp/import.txt' INTO TABLE Auteur FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE '/tmp/import.txt' INTO TABLE Directeur FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE '/tmp/import.txt' INTO TABLE Acteur FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE '/tmp/import.txt' INTO TABLE Oeuvre FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE '/tmp/import.txt' INTO TABLE Film FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE '/tmp/import.txt' INTO TABLE Serie FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE '/tmp/import.txt' INTO TABLE Episode FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE '/tmp/import.txt' INTO TABLE Pays FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE '/tmp/import.txt' INTO TABLE Genre FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n";

LOAD DATA LOCAL INFILE '/tmp/import.txt' INTO TABLE Langue FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n";